In [1]:
from pathlib import Path
import pandas as pd
from apply_geo_contract import apply_geo_contract_df

In [2]:


# analyze.ipynb is in format_data/place/, so go up one level to format_data/
fields_csv_path = Path("..") / "generated" / "fields.csv"

df = pd.read_csv(fields_csv_path)
df.head()

   objectId department  final_date      geo_options
0     44793  Asian Art          50  ||||||||China||
1     44817  Asian Art       -1750  ||||||||Japan||
2     44830  Asian Art         200  ||||||||Japan||
3     44862  Asian Art        1669  ||||||||Japan||
4     44907  Asian Art           0  ||||||||Japan||

In [3]:
df_with_geo = apply_geo_contract_df(df)
# New normalized columns: geo_normalized_*
df_with_geo.head()

,objectId,department,final_date,geo_options,geo_LLM_best_guess_location_normalized,geo_LLM_source_cols,geo_LLM_confidence,geo_LLM_geo_eligible
0,44793,Asian Art,50,||||||||China||,China,culture,0.55,true
1,44817,Asian Art,-1750,||||||||Japan||,Japan,culture,0.55,true
2,44830,Asian Art,200,||||||||Japan||,Japan,culture,0.55,true
3,44862,Asian Art,1669,||||||||Japan||,Japan,culture,0.55,true
4,44907,Asian Art,0,||||||||Japan||,Japan,culture,0.55,true

In [4]:
counts_geo_df = (   
    df_with_geo["geo_options"]
    # .fillna("")
    # .replace("", "EMPTY")
    .value_counts()
    .rename_axis("geo_options")
    .reset_index(name="count")
)

In [5]:
from IPython.display import display, HTML
display(HTML("<div style='max-height:500px; overflow:auto;'>" + counts_geo_df.to_html(index=False) + "</div>"))

In [6]:
counts_df = (
    df_with_geo["geo_normalized_best_guess_location"]
    # .fillna("")
    # .replace("", "EMPTY")
    .value_counts()
    .rename_axis("geo_normalized_best_guess_location")
    .reset_index(name="count")
)
# counts_df.head(20)

In [7]:
from IPython.display import display, HTML
display(HTML("<div style='max-height:500px; overflow:auto;'>" + counts_df.to_html(index=False) + "</div>"))