In [1]:
from pathlib import Path
import pandas as pd

csv_path = Path("object_function_groups.csv")
df = pd.read_csv(csv_path)

In [2]:
df.head()

,objectID,department,objectName,title,final_group
0,44793,Asian Art,Jar,Jar,jar
1,44817,Asian Art,Vessel,Spouted Vessel,vessel
2,44830,Asian Art,Jar,Jar,jar
3,44862,Asian Art,Hanging flower vase,Hanging Flower Holder (Hanaire) with Woman Hol...,vase
4,44907,Asian Art,Jar,Jar,jar

In [3]:
final_group_summary = (
    df["final_group"]
    .astype("string")
    .str.strip()
    .value_counts(dropna=False)
    .rename_axis("final_group")
    .reset_index(name="count")
)

final_group_summary["percent"] = (
    final_group_summary["count"] / len(df) * 100
).round(2)

final_group_summary

  final_group  count  percent
0        vase   1283    30.57
1         jar   1029    24.52
2      bottle    874    20.82
3         jug    340      8.1
4     pitcher    326     7.77
5       flask    113     2.69
6      vessel    101     2.41
7     amphora     67      1.6
8         pot     47     1.12
9      beaker     17     0.41